uploads = []
outputs = []

[[generated]]
id = "17Ojyzb5e_AqX3Fe_OTCf"
uri = "file://artifacts/nursery-showcase/src/assets/images/plant-1.png"
type = "image"
title = "Monstera Deliciosa studio photo"

[[generated]]
id = "0vEK1QNkQyAuNTnZ99NXT"
uri = "file://artifacts/nursery-showcase/src/assets/images/plant-2.png"
type = "image"
title = "Fiddle Leaf Fig studio photo"

[[generated]]
id = "ZVN4ulSjEWq4tPpuk9u72"
uri = "file://artifacts/nursery-showcase/src/assets/images/plant-3.png"
type = "image"
title = "Bird of Paradise studio photo"

[[generated]]
id = "i7awmKWgwsZDzPMzhyPvC"
uri = "file://artifacts/nursery-showcase/src/assets/images/plant-4.png"
type = "image"
title = "Calathea studio photo"

[[generated]]
id = "_SPUrxTIJmXZ1EVfrLXtS"
uri = "file://artifacts/nursery-showcase/src/assets/images/plant-5.png"
type = "image"
title = "Olive Tree studio photo"

[[generated]]
id = "scEGQfl95pX8LiHiNw7Ds"
uri = "file://artifacts/nursery-showcase/src/assets/images/plant-6.png"
type = "image"
title = "Philodendron studio photo"

[[generated]]
id = "SXRpV-0kEWbkTPKLb7gZH"
uri = "file://artifacts/nursery-showcase/src/assets/images/plant-7.png"
type = "image"
title = "Alocasia studio photo"

[[generated]]
id = "tdC0TnLn3YB-V_8fer5dK"
uri = "file://artifacts/nursery-showcase/src/assets/images/plant-8.png"
type = "image"
title = "ZZ plant studio photo"
